---
#-------------------------------
# General Site Settings
title: Jonas Steinhauser
logo: # You can add own logo. For example '/images/logo.png'.
description: Servus 👋, Ich bin Jonas Steinhauser! Geek & Developer. Meine Interessen liegen in Softwareentwicklung, DevOps und IoT.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jonas-steinhauser.de" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Jonas Steinhauser
  bio: Servus 👋, Ich bin Jonas Steinhauser! Geek & Developer. Meine Interessen liegen in Softwareentwicklung, DevOps und IoT.
  avatar: "/images/me.webp"

social:
  - {
      icon: "ion-logo-linkedin",
      label: LinkedIn,
      link: "https://de.linkedin.com/in/jonas-steinhauser-278b221ab",
    }
  - {
      icon: "ion-logo-xing",
      label: Xing,
      link: "https://www.xing.com/profile/Jonas_Steinhauser3",
    }
  - {
      icon: "ion-logo-github",
      label: GitHub,
      link: "https://github.com/JSCodesTech",
    }
  - {
      icon: "ion-logo-instagram",
      label: Instagram,
      link: "https://www.instagram.com/jscodestech/",
    }

# Example of adding a new link to the author section and footer - {icon: "ion-logo-github", label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: Servus 👋, Ich bin Jonas Steinhauser! Geek & Developer.
  hero__description: In diesem Blog schreibe ich über alles, was mich so interessiert. Es sind Themen wie Softwareentwicklung, DevOps und IoT dabei.
  hero__image: "/images/me.webp"

#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp: false # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp__title: Get interesting news # Add your Title
mailchimp__text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Join # Add your button text

#-------------------------------
# Contact Settings
contact:
  email: info@jonas-steinhauser.de # Add your email for contact form
  description: Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-minifier
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title

sass:
  sass_dir: _sass
  style: compressed

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 25

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/images"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  # Eg : "/usr/local/bin/cwebp"
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################
